WIP: Derivation for sum that consists only of singletons
propensive/wisteria pull request #19
Opened 2024-06-02 17:24 UTC by NPCRUS

**WIP: This is by any means not a final version of implementation. Moreover - I'm not sure at all that it should be ever merged. I will raise multiple comments and questions for implementation and possible issues below**

The only possible implementation that imho make sense is one presented in PR, where reader/producer typeclass derivation for Sum is simplified to the point, where typeclass for it's variants are not derived. Data from variants is being accessed within `split`
```
enum Test:
 case First
summon[Typeclass[Test]] //compiles
summon[Typeclass[Test.First.type]] // doesn't compile
```

Questions:
- how can `SimpleSumDerivation` fit together with existing `ProductDerivation` and `Derivation`, so that we need to retain `given derived[T]`

2024-06-02 17:25 UTC, NPCRUS commented on src/core/wisteria.SimpleSumDerivationMethods.scala
> +                    summonInline[SingletonFactory[VariantType]].create
is there any other way to narrow down `VariantType` to singleton

2024-06-12 19:04 UTC, NPCRUS commented on src/test/tests.scala
> +  val compilationError = summon[Show[Adt]]
should I just leave a happy path for now. I don't see any simple way for now to check that this fails in compile time without failing whole suite

2024-06-15 16:23 UTC, propensive requested changes
Looks mostly good, thank you! I haven't commented on the documentation, as I'll probably make a couple of changes to that before I merge, but I'm glad you didn't miss it! I think the changes I mentioned shouldn't be too much work, and if they don't work for some reason, we can just leave things as they are.

2024-06-15 16:23 UTC, propensive commented on src/core/wisteria.SumDerivationMethods.scala
> +  private transparent inline def fold[VariantType, VariantTypes <: Tuple]: Boolean =
Can you inline the `fold` method? (Here "inline" means "manually write its body in the one place it's used.") Since it's only called by `allSingletons`, and it's not general-purpose (like the other `fold` methods), I don't think it needs to be a separate method.

2024-06-15 16:23 UTC, propensive commented on src/core/wisteria.SumDerivationMethods.scala
> +        case given (VariantType <:< Singleton) =>
Rather than use `summonFrom`, is it possible to do an inline `erasedValue` pattern match to check if it's `Singleton`? I'm not sure if there's any practical difference, but it should be more direct.

2024-06-15 16:23 UTC, propensive commented on src/test/tests.scala
> +  val compilationError = summon[Show[Adt]]
Leave it as it is for now. I have a compiler plugin which allows you to test things like this by wrapping them in a `demilitarize` block which captures the compile errors as values, but I haven't published it yet. But it's a matter of days rather than weeks.

2024-06-15 16:26 UTC, NPCRUS commented on src/core/wisteria.SumDerivationMethods.scala
> +        case given (VariantType <:< Singleton) =>
I had the same idea, and I've tried countless ways, but somehow only this works

2024-06-16 05:45 UTC, merged